# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb2188df4f4b40f1b113fa601d91bba45be75de18297d3a28965f3f742587efeee609bdebe19b908f10194006fa65b5b711d91c2282823a03547c7630b66a083

test:
  secret_key_base: 33ed862277f8d0920fd2b2f3d4c4c4be5cd4d018d274a6d35afa4f2acb02060cd4b4c84797d1443325bc13b7d007edebe4b948cd23f6e0da3e1ac0061892ddcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
